# Welcome to Jekyll!
#

# Site settings
title: Impressions
headline: |
  Targeted Advertising Agency
description: Impressions is an online advertising service that enables advertisers to reach their niche user-base in an integrated method in e-commerce platforms.
logo: /images/impressions_logo_white.png
owner: Information Business # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ipay@ib.sa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://impressions.io" # the base hostname & protocol for your site
project-url: http://ib.sa/projects/impressions
contact-url: http://ib.sa/#contact
social:
  twitter: https://twitter.com/InforBizness
  github: https://github.com/iBizness
  linkedin-square: https://linkedin.com/company/information-business
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
